apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envoyProxy.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.componentLabels" (dict "context" . "component" .Values.envoyProxy.name) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 9901
    targetPort: admin
    protocol: TCP
    name: admin
  selector:
    {{- include "openchoreo-control-plane.componentSelectorLabels" (dict "context" . "component" .Values.envoyProxy.name) | nindent 4 }}
